### ISSUE TITLE
Überschreiben von Dateien

### ISSUE THREAD

**Issue by Scriptor1000** [Sakulboss/Semi10#3]
Das aktuelle Python Skript überschreibt immer die Dateien. Mann kann das ändern, in dem man nach vorhandenen Dateien scannt und entsprechend die Nummer im Dateinamen anpasst.
Beispielsweise mithilfe dieser Funktion:
````
import os

def get_new_filename(file_extension: str) -> str:
	count = len([i for i in os.listdir() if i.endswith(file_extension)])
	return f'output_{count}.{file_extension}'
````

**Comment by Sakulboss** [comment]
Ich überschreibe dich gleich, aber das hat den ZWeck, das wir nicht lange suchen müssen
